<a href="https://colab.research.google.com/github/Mohamad-Selawy/Python/blob/master/Data%20Analysis/Level%201/data_types_and_conversions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Types & Conversions in Pandas
Understanding and managing data types correctly is essential for accurate computations, memory efficiency, and proper data analysis. Pandas supports various data types such as integers, floats, strings (objects), categorical data, and datetime formats.

## 1. Common Pandas Data Types

| Data Type    | Description                               |
| ------------ | ----------------------------------------- |
| `int64`      | Integer numbers                           |
| `float64`    | Decimal numbers                           |
| `object`     | Text/string data (general Python objects) |
| `bool`       | Boolean values (`True`/`False`)           |
| `category`   | Categorical (finite, repeated values)     |
| `datetime64` | Date and time values                      |


### Example

In [29]:
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol'],
    'Age': ['25', '32', '40'],
    'Score': [88.5, 92.0, 79.5],
    'Passed': ['Yes', 'No', 'Yes'],
    'ExamDate': ['2025-07-01', '2025-07-02', '2025-07-03']
})

df.dtypes

Name         object
Age          object
Score       float64
Passed       object
ExamDate     object
dtype: object

## 2. Type Conversions Using .astype()
### Convert to Integer or Float

In [30]:
df['Age'] = df['Age'].astype('int64')
df['Score'] = df['Score'].astype('float64')
df['Age']

0    25
1    32
2    40
Name: Age, dtype: int64

In [31]:
df['Score']

0    88.5
1    92.0
2    79.5
Name: Score, dtype: float64

### Convert String to Categorical (saves memory)

The `category` data type in Pandas is used for columns that contain a limited number of unique values, which are often repeated many times. Examples include 'Yes'/'No', 'Male'/'Female', or colors like 'Red'/'Green'/'Blue'.

**Key benefits of using `category` data type:**

*   **Memory Efficiency:** For columns with many repeated values, storing them as categorical types can significantly reduce memory usage compared to storing them as `object` (string) types.
*   **Performance:** Some operations on categorical data can be faster than on object data, especially when sorting or performing certain statistical computations.
*   **Data Validation:** It can help in ensuring data consistency by limiting entries to a predefined set of categories.

In the example, the 'Passed' column was converted to `category` because it only contains 'Yes' and 'No', which are finite and repeated values. This is a good practice for such columns.

In [ ]:
df['Passed'] = df['Passed'].astype('category')
df['Passed']

0    Yes
1     No
2    Yes
Name: Passed, dtype: category
Categories (2, object): ['No', 'Yes']

### Convert to Boolean

In [ ]:
df['PassedBool'] = df['Passed'].map({'Yes': True, 'No': False})
df['PassedBool']

0     True
1    False
2     True
Name: PassedBool, dtype: category
Categories (2, bool): [False, True]

## 3. Converting to DateTime

Working with time-series or dates? Convert string columns to datetime:

In [27]:
df['ExamDate'] = pd.to_datetime(df['ExamDate'])
df['ExamDate'].dt.year  # Access datetime components

0    2025
1    2025
2    2025
Name: ExamDate, dtype: int32

## 4. Error Handling in Conversion
You can control how Pandas handles errors during conversion:

When using `pd.to_datetime()` with `errors='coerce'`, Pandas will convert any invalid date formats it encounters into `NaT` (Not a Time) values instead of raising an error. This is useful for cleaning messy date columns where some entries might not be parseable as dates, allowing the conversion to proceed without crashing and highlighting the problematic entries with `NaT`.

In [34]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Carol'],
    'Age': ['25', '32', '40'],
    'Score': [88.5, 92.0, 79.5],
    'Passed': ['Yes', 'No', 'Yes'],
    'ExamDate': ['2025-07-01', 'not a date', '2025-07-03']
})
df

    Name Age  Score Passed    ExamDate
0  Alice  25   88.5    Yes  2025-07-01
1    Bob  32   92.0     No  not a date
2  Carol  40   79.5    Yes  2025-07-03

In [35]:
# Force conversion, invalid parsing returns NaT
df['ExamDate'] = pd.to_datetime(df['ExamDate'], errors='coerce')
df

    Name Age  Score Passed   ExamDate
0  Alice  25   88.5    Yes 2025-07-01
1    Bob  32   92.0     No        NaT
2  Carol  40   79.5    Yes 2025-07-03

In [36]:
print('--- Rows with NaT in ExamDate ---')
df_nat_dates = df[pd.isnull(df['ExamDate'])]
display(df_nat_dates)

--- Rows with NaT in ExamDate ---

  Name Age  Score Passed ExamDate
1  Bob  32   92.0     No      NaT

## Summary

| Conversion Task            | Method                               |
| -------------------------- | ------------------------------------ |
| String to int/float        | `.astype('int')`, `.astype('float')` |
| String to category         | `.astype('category')`                |
| String to boolean          | `.map()` or `.astype('bool')`        |
| String to datetime         | `pd.to_datetime()`                   |
| Handling conversion errors | `errors='coerce'`                    |