<a href="https://colab.research.google.com/github/Mohamad-Selawy/Python/blob/master/Data%20Analysis/Level%201/Pandas_for_Data_Analysis_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas for Data Analysis
This notebook provides a beginner-friendly walkthrough of key pandas functionalities using simple examples. Topics include:
- Reading data from CSV, Excel, and JSON
- Selecting and filtering rows and columns
- Merging, concatenating datasets
- Grouping and aggregating data
- Applying functions with `.apply()`, `.map()`, and `.lambda`
- Transforming data with `.pivot()`, `.melt()`

In [9]:
# Importing required libraries
import pandas as pd
import json

## Reading Data
We'll create small example files and read them using pandas.

In [10]:
# Create example CSV file
csv_data = '''Name,Age,Salary
Alice,25,50000
Bob,30,60000
Charlie,35,70000'''
with open('example.csv', 'w') as f:
    f.write(csv_data)

# Read CSV
df_csv = pd.read_csv('example.csv')
df_csv

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [11]:
# Create example Excel file
df_csv.to_excel('example.xlsx', index=False)

# Read Excel
df_excel = pd.read_excel('example.xlsx')
df_excel

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [12]:
# {'Key': 'Values'}

In [13]:
# Create example JSON file
json_data = df_csv.to_dict(orient='records')
with open('example.json', 'w') as f:
    json.dump(json_data, f)

# Read JSON
df_json = pd.read_json('example.json')
df_json

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

## Selecting and Filtering Rows and Columns

### Explanation of Selecting and Filtering Rows and Columns

*   **Selecting Columns**: In pandas, you can select one or more columns by using single or double square brackets with the column names. This returns a Series for a single column or a DataFrame for multiple columns.
*   **Filtering Rows**: You can filter rows based on a condition, which typically involves providing a boolean Series inside square brackets. Only rows where the condition is `True` will be returned.

In [14]:
df_csv

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [15]:
# Selecting columns
df_csv['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object

In [16]:
# Selecting multiple columns
df_csv[['Name', 'Age']]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [17]:
df_csv

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [18]:
# Filtering rows where Age > 28
df_csv[df_csv['Age'] > 28]

      Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   70000

In [19]:
df_csv

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [20]:
df_csv['Age'] > 28

0    False
1     True
2     True
Name: Age, dtype: bool

In [21]:
df_csv['Salary'] > 60000

0    False
1    False
2     True
Name: Salary, dtype: bool

In [22]:
# Filtering rows with multiple conditions (Age > 28 AND Salary > 60000)
df_csv[(df_csv['Age'] > 28) | (df_csv['Salary'] > 60000)]

      Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   70000

## Merging and Concatenating

### Explanation of Merging, Joining, and Concatenating

*   **Merging (`pd.merge()`)**: Used to combine two DataFrames based on common columns (keys). It's similar to SQL joins and offers various types (inner, outer, left, right).

*   **Concatenating (`pd.concat()`)**: Stacks DataFrames either vertically (row-wise) or horizontally (column-wise) along an axis. It's used to append or stack multiple DataFrames directly.

In [23]:
# Create another DataFrame
dept = pd.DataFrame({'Name': ['Bob', 'Alice', 'Charlie', 'Alice'], 'Dept': ['HR', 'IT', 'Finance', 'CEO']})
print(dept)
print()
print(df_csv)
# Merge on 'Name'
pd.merge(df_csv, dept, on='Name')

      Name     Dept
0      Bob       HR
1    Alice       IT
2  Charlie  Finance
3    Alice      CEO

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

      Name  Age  Salary     Dept
0    Alice   25   50000       IT
1    Alice   25   50000      CEO
2      Bob   30   60000       HR
3  Charlie   35   70000  Finance

In [24]:

# Prepare an additional DataFrame to demonstrate outer, left, and right merges clearly
df_salaries = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie', 'David'],
                            'Salary_2023': [52000, 61000, 72000, 55000]})

df_departments = pd.DataFrame({'Name': ['Alice', 'Bob', 'Eve'],
                                'Department': ['HR', 'IT', 'Marketing']})


print("DataFrames for merge examples:")
print("df_salaries:")
print(df_salaries)
print("\ndf_departments:")
print(df_departments)
print("\n")

print("Inner Merge (default):")
# Inner merge: Returns only the rows that have matching keys in both DataFrames.
merged_inner = pd.merge(df_salaries, df_departments, on='Name', how='inner')
print(merged_inner)
print("\n")

print("Outer Merge:")
# Outer merge: Returns all rows when there is a match in one of the DataFrames.
# If there is no match, the row is included with NaN values for the non-matching DataFrame's columns.
merged_outer = pd.merge(df_salaries, df_departments, on='Name', how='outer')
print(merged_outer)
print("\n")

print("Left Merge:")
# Left merge: Returns all rows from the left DataFrame, and the matching rows from the right DataFrame.
# If there is no match in the right DataFrame, NaN values are used for its columns.
merged_left = pd.merge(df_salaries, df_departments, on='Name', how='left')
print(merged_left)
print("\n")

print("Right Merge:")
# Right merge: Returns all rows from the right DataFrame, and the matching rows from the left DataFrame.
# If there is no match in the left DataFrame, NaN values are used for its columns.
merged_right = pd.merge(df_salaries, df_departments, on='Name', how='right')
print(merged_right)

DataFrames for merge examples:
df_salaries:
      Name  Salary_2023
0    Alice        52000
1      Bob        61000
2  Charlie        72000
3    David        55000

df_departments:
    Name Department
0  Alice         HR
1    Bob         IT
2    Eve  Marketing


Inner Merge (default):
    Name  Salary_2023 Department
0  Alice        52000         HR
1    Bob        61000         IT


Outer Merge:
      Name  Salary_2023 Department
0    Alice      52000.0         HR
1      Bob      61000.0         IT
2  Charlie      72000.0        NaN
3    David      55000.0        NaN
4      Eve          NaN  Marketing


Left Merge:
      Name  Salary_2023 Department
0    Alice        52000         HR
1      Bob        61000         IT
2  Charlie        72000        NaN
3    David        55000        NaN


Right Merge:
    Name  Salary_2023 Department
0  Alice      52000.0         HR
1    Bob      61000.0         IT
2    Eve          NaN  Marketing

In [25]:
df_csv

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [26]:
# Concatenate two dataframes vertically
pd.concat([df_csv, df_csv]).reset_index(drop=True)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
3    Alice   25   50000
4      Bob   30   60000
5  Charlie   35   70000

## Grouping and Aggregating

### Explanation of Grouping and Aggregating

*   **Grouping**: The process of categorizing data into groups based on one or more keys (columns). This is often done using the `.groupby()` method.
*   **Aggregating**: After grouping, aggregation involves applying a function (like sum, mean, count, min, max, etc.) to each group to produce a single result for each group. This summarizes the data within each category.

In [27]:
monthly_sales_data = {
    'month': ['Jan', 'Jan', 'Feb', 'Feb', 'Feb', 'Mar', 'Mar', 'Mar'],
    'product': ['A', 'B', 'A', 'B', 'A' , 'A', 'B', 'C'],
    'sales': [100, 150, 120, 180, 50, 110, 160, 40]
}
df_monthly_sales = pd.DataFrame(monthly_sales_data)
display(df_monthly_sales)

  month product  sales
0   Jan       A    100
1   Jan       B    150
2   Feb       A    120
3   Feb       B    180
4   Feb       A     50
5   Mar       A    110
6   Mar       B    160
7   Mar       C     40

In [28]:
df_monthly_sales_grouped_by_month = df_monthly_sales.groupby('month').agg(TotalSales=('sales', 'sum'))
display(df_monthly_sales_grouped_by_month)

       TotalSales
month
Feb           350
Jan           250
Mar           310

In [29]:
df_monthly_sales_grouped = df_monthly_sales.groupby(['month', 'product']).agg(TotalSales=('sales', 'sum'))
display(df_monthly_sales_grouped)

               TotalSales
month product
Feb   A               170
      B               180
Jan   A               100
      B               150
Mar   A               110
      B               160
      C                40

## Applying Functions: `.apply()`, `.map()`, `.lambda`

### Explanation of `.apply()`, `.map()`, and `lambda`

*   **`.apply()`**: Used to apply a function along an axis of the DataFrame (rows or columns) or on Series values. It's very flexible and can be used for more complex operations.
*   **`.map()`**: Primarily used with a Series to substitute each value in the Series with another value, either by using a dictionary or a Series. It's optimized for one-to-one substitutions.
*   **`lambda`**: An anonymous, small, single-expression function. It's often used as an argument to higher-order functions like `apply()` or `map()` for concise, on-the-fly function definitions.

In [30]:
# Using .apply with lambda
df_csv['Tax'] = df_csv['Salary'].apply(lambda x: x * 0.2)
df_csv

      Name  Age  Salary      Tax
0    Alice   25   50000  10000.0
1      Bob   30   60000  12000.0
2  Charlie   35   70000  14000.0

In [31]:
# Using .apply with lambda
df_csv['Range'] = df_csv['Salary'].apply(lambda x: 'High' if x >= 60000 else 'Low')
df_csv

      Name  Age  Salary      Tax Range
0    Alice   25   50000  10000.0   Low
1      Bob   30   60000  12000.0  High
2  Charlie   35   70000  14000.0  High

In [32]:
status_map = {25: 'Young', 30: 'Adult', 35: 'Senior'}
df_csv['Status'] = df_csv['Age'].map(status_map)
df_csv

      Name  Age  Salary      Tax Range  Status
0    Alice   25   50000  10000.0   Low   Young
1      Bob   30   60000  12000.0  High   Adult
2  Charlie   35   70000  14000.0  High  Senior

## Transforming Data: `.pivot()`, `.melt()`

### Explanation of Data Transformation Functions

*   **`.pivot()`**: Reshapes data based on column values. It creates a new table where unique values from one column become new columns, unique values from another column become the index, and values from a third column populate the new table.
*   **`.melt()`**: Unpivots a DataFrame from a 'wide' format to a 'long' format. It makes column headers into row values, useful for transforming data for visualization or analysis.

In [33]:
monthly_sales_data = {
    'month': ['Jan', 'Jan', 'Feb', 'Feb', 'Mar', 'Mar'],
    'product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'sales': [100, 150, 120, 180, 110, 160]
}
df_monthly_sales = pd.DataFrame(monthly_sales_data)
display(df_monthly_sales)

  month product  sales
0   Jan       A    100
1   Jan       B    150
2   Feb       A    120
3   Feb       B    180
4   Mar       A    110
5   Mar       B    160

#### Pivoted Data: Transforming 'Long' to 'Wide' Format

In [36]:
# Pivot the melted DataFrame back to a wide format
pivoted_monthly_sales = df_monthly_sales.pivot(index='month', columns='product', values='sales')
pivoted_monthly_sales

product    A    B
month
Feb      120  180
Jan      100  150
Mar      110  160

#### Melted Data: Transforming 'Wide' to 'Long' Format

In [37]:
# Reset the index to make 'month' a regular column again
unpivoted_df = pivoted_monthly_sales.reset_index()

# Melt the DataFrame to transform it back to a long format
# 'month' is the identifier variable
# The column headers ('A', 'B') become values in the 'product' column
# The cell values become values in the 'sales' column
result_df = unpivoted_df.melt(id_vars=['month'], var_name='product', value_name='sales')
result_df

  month product  sales
0   Feb       A    120
1   Jan       A    100
2   Mar       A    110
3   Feb       B    180
4   Jan       B    150
5   Mar       B    160